# -*- coding: utf-8 -*-
"""dsp_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a9_6U2BVumm6LqLTy7cp8MEWdd2AXoiD

# ローカルデータ
"""

#SQLiteをインポート
import sqlite3

#自分の位置を確認
!pwd

#パスを設定
path='/content/'
#DBファイル名を設定
db_name='local_data.sqlite'
#DBへ接続
con=sqlite3.connect(path+db_name)
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトの取得
cur=con.cursor()
#テーブルの作成
sql_create_table_local='CREATE TABLE local(Date date,Rising_time time,Retiring_time time);'
#SQLの実行
cur.execute(sql_create_table_local)
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトの取得
cur=con.cursor()
#データ入力のSQL
sql_insert_local="INSERT INTO local VALUES(?,?,?);"
#データリストの作成
local_list=[
    ('2023-12-20','7:00','23:00'),
    ('2023-12-21','5:30','23:01'),
    ('2023-12-22','5:30','23:07'),
    ('2023-12-23','5:00','23:23'),
    ('2023-12-24','7:30','23:41'),
    ('2023-12-25','7:00','23:02'),
    ('2023-12-26','7:30','22:30'),
    ('2023-12-27','5:30','23:00'),
    ('2023-12-28','8:00','23:45'),
    ('2023-12-29','7:00','23:15'),
    ('2023-12-30','7:00','23:43'),
    ('2023-12-31','8:00','23:06'),
    ('2024-01-01','7:00','23:03'),
    ('2024-01-02','7:00','23:04'),
    ('2024-01-03','7:00','23:30'),
    ('2024-01-04','8:00','23:22'),
    ('2024-01-05','8:00','23:50'),
    ('2024-01-06','5:00','23:13'),
    ('2024-01-07','7:00','23:19'),
    ('2024-01-08','7:00','23:26'),
    ('2024-01-09','7:30','23:08'),
]
#SQLの実行
cur.executemany(sql_insert_local,local_list)
#コミット
con.commit()
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトの取得
cur=con.cursor()
#データの参照
sql_select_local='SELECT * FROM local;'
#SQLの実行
cur.execute(sql_select_local)
#データの表示
for l in cur:
  print(l)
#接続を閉じる
con.close()

"""# スクレイピング"""

from bs4 import BeautifulSoup
import requests

#URL
url='https://banno-clinic.biz/university-student-sleep/#:~:text=%E3%81%93%E3%81%AE%E7%B5%B1%E8%A8%88%E3%83%87%E3%83%BC%E3%82%BF%E3%81%8B%E3%82%89%E8%A8%88%E7%AE%97,%E5%88%86%E3%81%A8%E6%A6%82%E7%AE%97%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99%E3%80%82'
#リクエスト
r = requests.get(url)

#情報の取得
html_soup=BeautifulSoup(r.text,'html.parser')
print(type(html_soup))

#pタグの情報取得
p=html_soup.find_all("p",limit=13)
print(type(p))
print(p)

"""# オープンデータ"""

#パスの設定
path='/content/'
#DBファイル名を設定
db_name='open_data.sqlite'
#DBへ接続
con=sqlite3.connect(path+db_name)
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトの取得
cur=con.cursor()
#テーブルの作成
sql_create_table_open='CREATE TABLE open(Average_risnig_time time,Average_retiring_time time);'
#SQLの実行
cur.execute(sql_create_table_open)
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトを取得
cur=con.cursor()
#データの入力
sql_insert_open="INSERT INTO open VALUES ('7:56','0:31');"
#SQLの実行
cur.execute(sql_insert_open)
#コミット
con.commit()
#接続を閉じる
con.close()

#DBへ接続
con=sqlite3.connect(path+db_name)
#SQLを実行するためのオブジェクトを取得
cur=con.cursor()
#データの参照
sql_select_open='SELECT * FROM open;'
#SQLの実行
m=cur.execute(sql_select_open)
#データの表示
for m in cur:
  print(m)
#接続を閉じる
con.close()

"""# 可視化"""

#pandasとmatplotlibをインポート
import pandas as pd
import matplotlib.pyplot as plt

#csvの読み込みと表示
df=pd.read_csv('/content/dsp_final_local .csv')
df

#1つ前のセルの実行結果からグラフを描画する機能を使った(自分でもコードを書いてみたのですが、全く綺麗に描画できなかったのでこの機能を使いました)
from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('time_1').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

#前とセルと同様の機能を使用してtime_2のグラフを描画
from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('time_2').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

"""# 結果と考察

20~24歳の平均の起床時間、就寝時間と自分自身の睡眠に関するデータを比較すると、自分は早寝早起きの方に分類されるのではないかと考えられる。また、起床時間はある程度決まった時間帯に集中しているのに対し、就寝時間は分散していた。これらの結果の考察として、早朝のアルバイトや大学の1限の授業に間に合うように目覚ましをかけていたり、就寝時間を決めていないためだと考えられる。就寝時間も決めることでしっかりとした睡眠時間を確保でき、健康的な生活リズムを作ることができるのではないかと考えた。

# その他

資料：大学生の理想の睡眠時間が分かります | 阪野クリニック
https://banno-clinic.biz/university-student-sleep/#:~:text=この統計データから計算,分と概算されます%E3%80%82
(参照:2024-01-14) (更新:2023-01-16)

協力した人:横山広樹(学籍番号:2322106)
"""